#!usr/bin/env python3 
  
 import os 
  
 os.system("pkg install ruby -y") 
 os.system("gem install lolcat") 
 os.system("pip install --upgrade pip") 
 os.system("pip install colorama") 
 os.system("pip2 install lolcat") 
 os.system("pkg install cowsay") 
  
 import colorama 
  
 from colorama import Fore, Back, Style 
  
 os.system("clear") 
 os.system("cowsay -f eyes Termux Ilk Kuruluma Hosgeldiniz.  | lolcat -a -d 4") 
  
 print(" ") 
  
 os.system("printf 'Yuklenecek Paketler: \n python2 \n fish \n ruby \n php \n perl \n nmap \n bash \n clang \n nano \n curl \n tar \n zip \n unzip \n tor \n wget \n wcalc \n bmon \n golang \n openssl \n openssh \n toilet \n sl \n vim \n zsh \n fortune' | lolcat -a -d 10") 
  
 print(" ") 
  
  
 colorama.init(autoreset=True) 
  
 print(" ") 
  
 input(Fore.CYAN +Style.BRIGHT + "Kurulumu baslatmak icin Enter'a basiniz....") 
  
  
  
 os.system("pkg update -y") 
 os.system("pkg upgrade -y") 
 os.system("clear") 
 os.system("pkg install pip")
 os.system("clear")
 os.system("pkg install pip2")
 os.system("clear")
 os.system("pkg install python2 -y") 
 os.system("clear")
 os.system("pkg install python -y") 
 os.system("clear") 
 os.system("pkg install python3 -y") 
 os.system("clear") 
 os.system("pkg install fish -y") 
 os.system("clear") 
 os.system("pkg install ruby -y") 
 os.system("clear") 
 os.system("pkg install git -y") 
 os.system("clear") 
 os.system("pkg install php -y") 
 os.system("clear") 
 os.system("pkg install perl -y") 
 os.system("clear") 
 os.system("pkg install nmap -y") 
 os.system("clear") 
 os.system("pkg install bash -y") 
 os.system("clear") 
 os.system("pkg install clang -y") 
 os.system("clear") 
 os.system("pkg install nano -y") 
 os.system("clear") 
 os.system("pkg install cowsay -y") 
 os.system("clear") 
 os.system("pkg install curl -y") 
 os.system("clear") 
 os.system("pkg install tar -y") 
 os.system("clear") 
 os.system("pkg install zip -y") 
 os.system("clear")   
 os.system("pkg install unzip -y") 
 os.system("clear") 
 os.system("pkg install tor -y") 
 os.system("clear") 
 os.system("pkg install wget -y") 
 os.system("clear") 
 os.system("pkg install wcalc -y") 
 os.system("clear") 
 os.system("pkg install bmon -y") 
 os.system("clear") 
 os.system("pkg install golang -y") 
 os.system("clear") 
 os.system("pkg install openssl -y") 
 os.system("clear") 
 os.system("pkg install openssh -y") 
 os.system("clear") 
 os.system("pkg install toilet -y") 
 os.system("clear") 
 os.system("pkg install sl -y") 
 os.system("clear") 
 os.system("pkg install vim -y") 
 os.system("clear") 
 os.system("pkg install zsh -y") 
 os.system("clear") 
 os.system("pkg install fortune -y") 
 os.system("clear") 
 os.system("pkg install tmate -y") 
 os.system("clear") 
 os.system("apt update -y") 
 os.system("clear") 
 os.system("apt upgrade -y") 
 os.system("clear") 
 os.system("git clone https://github.com/ByCh4n/BCHackTool"")
 os.system("cd BCHackTool")
 os.system("chmod +x bchacktool-termux.sh")
 os.system("cd")
 os.system("clear")
 os.system("git clone https://github.com/Bora185/Z-Bomb.git")
 os.system("cd Z-Bomb")
 os.system("pip3 install -r requirements.txt")
 os.system("cd")
 os.system("clear")
 os.system("git clone https://github.com/tingirifistik/Enough.git")
 os.system("cd Enough")
 os.system("pip3 install -r requirements.txt")
 os.system("cd")
 os.system("clear")
 os.system("git clone https://github.com/samsesh/SocialBox-Termux.git")
 os.system("cd SocialBox-Termux")
 os.system("chmod +x install-sb.sh")
 os.system("cd")
 os.system("clear")
 os.system("pip2 install requests")
 os.system("pip2 install mechanize")
 os.system("git clone https://github.com/ShTasrif/cybersh")
 os.system("cd cybersh")
 os.system("pip install -r requirements.txt")
 os.system("cd")
 os.system("clear")
 os.system("printf 'Kurulum Bitmistir..  ~~ MakinistBey ~~' | lolcat -a -d 70") 
  
 print(" ")